In [1]:
!pip install selenium

Requirement already satisfied: selenium in c:\users\hp\anaconda3\lib\site-packages (4.10.0)
Requirement already satisfied: urllib3[socks]<3,>=1.26 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (1.26.16)
Requirement already satisfied: trio~=0.17 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.22.2)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (0.10.3)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\hp\anaconda3\lib\site-packages (from selenium) (2023.5.7)
Requirement already satisfied: attrs>=20.1.0 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (22.1.0)
Requirement already satisfied: sortedcontainers in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: idna in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.4)
Requirement already satisfied: outcome in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sniffio in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: cffi>=1.14 in c:\users\hp\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.1)
Requirement already satisfied: exceptiongroup in c:\users\hp\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.1.2)
Requirement already satisfied: wsproto>=0.14 in c:\users\hp\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\hp\anaconda3\lib\site-packages (from urllib3[socks]<3,>=1.26->selenium) (1.7.1)
Requirement already satisfied: pycparser in c:\users\hp\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\hp\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [163]:
import selenium
import pandas as pd
from selenium import webdriver
import time
from selenium.common.exceptions import NoSuchElementException
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import requests
import regex as re

In [141]:
driver = webdriver.Chrome()

# Question 1

In [4]:
user = input("Enter your item: ")

Enter your item: Guitar

# Question 2

In [216]:
driver.get("https://www.amazon.in")

In [217]:
role1=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[2]/div[1]/input')
role1.send_keys('Guitar')

role2=driver.find_element(By.XPATH,'/html/body/div[1]/header/div/div[1]/div[2]/div/form/div[3]/div/span/input')
role2.click()

The history saving thread hit an unexpected error (OperationalError('database or disk is full')).History will not be written to the database.

In [218]:
page_url=[]
start = 0
end = 3
for page in range(start,end):
    
    url=driver.find_elements(By.XPATH,'//a[@class="a-link-normal s-underline-text s-underline-link-text s-link-style a-text-normal"]')
    for i in url:
        page_url.append(i.get_attribute('href'))
next_button=driver.find_element(By.XPATH,'//a[@class="s-pagination-item s-pagination-next s-pagination-button s-pagination-separator"]')
next_button.click()

In [219]:
len(page_url)

210

In [220]:
Brand=[]
Title=[]
Price=[]
Replacement=[]
Stock=[]
Delivery=[]

In [221]:

for i in page_url:
    driver.get(i)
    
    try:
        title=driver.find_element(By.XPATH,'//span[@class="a-size-large product-title-word-break"]')
        Title.append(title.text)
    except NoSuchElementException:
        Title.append('-')
        
    try:
        brand=driver.find_element(By.XPATH,'//*[@id="productOverview_feature_div"]/div/table/tbody/tr[1]/td[2]/span')
        Brand.append(brand.text)
    except NoSuchElementException:
        Brand.append('-')
        
        
    try:
        price=driver.find_element(By.XPATH,'//div[@id="corePrice_feature_div"]')
        Price.append(price.text.split('\n')[0])
    except NoSuchElementException:
        Price.append('-')
        
        
    try:
        replace=driver.find_element(By.XPATH,'//*[@id="iconfarmv2_feature_div"]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/ol/li[3]/div[1]/span/div[2]/span')
        Replacement.append(replace.text)
    except NoSuchElementException:
        Replacement.append('-')
        
        
        
    try:
        stock=driver.find_element(By.XPATH,'//div[@class="a-section a-spacing-none a-spacing-top-micro }"]')
        Stock.append(stock.text)
    except NoSuchElementException:
        Stock.append('-')
        
        
    try:
        delivery=driver.find_element(By.XPATH,'//*[@id="deliveryBlockContainer"]/div[1]/div[1]/div[1]/div[1]/span/span[1]')
        Delivery.append(delivery.text)
    except NoSuchElementException:
        Delivery.append('-')

In [222]:
print(len(Brand),len(Delivery),len(Stock),len(Price),len(Title),len(Replacement))

210 210 210 210 210 210

In [223]:
df=pd.DataFrame({"Brand Name":Brand,"Name of the Product":Title,"Price":Price,"Return/Exchange":Replacement,"Expected Delivery":Delivery,"Availability":Stock,"Product URL":page_url})
df

,Brand Name,Name of the Product,Price,Return/Exchange,Expected Delivery,Availability,Product URL
0,Kadence,Kadence Frontier guitar with Online Guitar lea...,"₹5,199",7 days Replacement,"Monday, 14 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
1,VAULT,Vault DA20 Dreadnought Acoustic Guitar With Gi...,"₹4,899",7 days Replacement,"Sunday, 13 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
2,Henrix,Henrix 38C 38 Inch Cutaway Acoustic Guitar Wit...,"₹2,999",7 days Replacement,"Sunday, 13 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
3,Ibanez,Ibanez MD39C-NT 39 Inches Rose Wood Cutaway Ac...,"₹7,699",7 days Replacement,"Sunday, 13 August",In stock,https://www.amazon.in/sspa/click?ie=UTF8&spc=M...
4,JUAREZ,"Juârez Acoustic Guitar, 38 Inch Cutaway, 038C ...","₹1,999",7 days Replacement,"Tuesday, 15 August",In stock,https://www.amazon.in/Juarez-Acoustic-Cutaway-...
...,...,...,...,...,...,...,...
205,Valencia,Valencia 200 Series 3/4 Size Classical Acousti...,"₹5,407",7 days Replacement,"Tuesday, 15 August",In stock,https://www.amazon.in/Valencia-Classical-Acous...
206,JUAREZ,"Juârez Acoustic Guitar, 38 Inch Cutaway, 038C ...","₹1,999",7 days Replacement,"Tuesday, 15 August",In stock,https://www.amazon.in/Juarez-Acoustic-Cutaway-...
207,Intern,"Intern INT-38C Right hand Acoustic Guitar Kit,...","₹2,099",7 days Replacement,"Tuesday, 15 August",In stock,https://www.amazon.in/Intern-INT-38C-Acoustic-...
208,YAMAHA,"Yamaha F280 Acoustic Rosewood Guitar (Natural,...","₹7,099",7 days Replacement,"Tuesday, 15 August",In stock,https://www.amazon.in/Yamaha-F280-Acoustic-Gui...
209,JUAREZ,"Juarez Lindenwood Acoustic Guitar Kit, 38 Inch...","₹1,999",7 days Replacement,"Tuesday, 15 August",In stock,https://www.amazon.in/JUAREZ-JRZ38C-Acoustic-S...

In [227]:
df.to_csv('question2.csv')

# Question 3

In [13]:
driver.get("https://images.google.com")

In [14]:
role21= driver.find_element(By.XPATH,'//textarea[@class="gLFyf"]')
role21.send_keys('fruits')

role22=driver.find_element(By.XPATH,'//div[@class="zgAlFc"]')
role22.click()

In [20]:
image_urls=[]

for _ in range(20):
    driver.execute_script("window.scrollBy(0,100)")
images=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')

for image in images:
    source=image.get_attribute('src')
    if source is not None:
        if (source[0:4] == 'http'):
            image_urls.append(source)
            
            
for i in range(len(image_urls)):
    if i>10:
        break
    print("Downloading {0} of {1} images" .format(i, 10))
    response=requests.get(image_urls[i])
    file = open(r"C:\Users\hp\OneDrive\Desktop\down"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [4]:
driver.get("https://images.google.com")

In [5]:
role23= driver.find_element(By.XPATH,'//textarea[@class="gLFyf"]')
role23.send_keys('cars')

role24=driver.find_element(By.XPATH,'//div[@class="zgAlFc"]')
role24.click()

In [9]:
cars_urls=[]

for _ in range(20):
    driver.execute_script("window.scrollBy(0,100)")
car=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')

for i in car:
    source=i.get_attribute('src')
    if source is not None:
        if (source[0:4] == 'http'):
            cars_urls.append(source)
            
            
for i in range(len(cars_urls)):
    if i>10:
        break
    print("Downloading {0} of {1} images" .format(i, 10))
    response=requests.get(cars_urls[i])
    file = open(r"C:\Users\hp\OneDrive\Desktop\down"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [13]:
driver.get("https://images.google.com")

In [14]:
role25= driver.find_element(By.XPATH,'//textarea[@class="gLFyf"]')
role25.send_keys('machine learning')

role26=driver.find_element(By.XPATH,'//div[@class="zgAlFc"]')
role26.click()

In [15]:
machine_learning=[]

for _ in range(20):
    driver.execute_script("window.scrollBy(0,100)")
machine=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')

for i in machine:
    source=i.get_attribute('src')
    if source is not None:
        if (source[0:4] == 'http'):
            machine_learning.append(source)
            
            
for i in range(len(machine_learning)):
    if i>10:
        break
    print("Downloading {0} of {1} images" .format(i, 10))
    response=requests.get(machine_learning[i])
    file = open(r"C:\Users\hp\OneDrive\Desktop\down"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [16]:
driver.get("https://images.google.com")

In [17]:
role27= driver.find_element(By.XPATH,'//textarea[@class="gLFyf"]')
role27.send_keys('guitar')

role28=driver.find_element(By.XPATH,'//div[@class="zgAlFc"]')
role28.click()

In [19]:
guitar=[]

for _ in range(20):
    driver.execute_script("window.scrollBy(0,100)")
g=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')

for i in g:
    source=i.get_attribute('src')
    if source is not None:
        if (source[0:4] == 'http'):
            guitar.append(source)
            
            
for i in range(len(guitar)):
    if i>10:
        break
    print("Downloading {0} of {1} images" .format(i, 10))
    response=requests.get(guitar[i])
    file = open(r"C:\Users\hp\OneDrive\Desktop\down"+str(i)+".jpg","wb")
    file.write(response.content)

Downloading 0 of 10 images
Downloading 1 of 10 images
Downloading 2 of 10 images
Downloading 3 of 10 images
Downloading 4 of 10 images
Downloading 5 of 10 images
Downloading 6 of 10 images
Downloading 7 of 10 images
Downloading 8 of 10 images
Downloading 9 of 10 images
Downloading 10 of 10 images

In [20]:
driver.get("https://images.google.com")

In [21]:
role29= driver.find_element(By.XPATH,'//textarea[@class="gLFyf"]')
role29.send_keys('cakes')

role30=driver.find_element(By.XPATH,'//div[@class="zgAlFc"]')
role30.click()

In [ ]:
cakes=[]

for _ in range(20):
    driver.execute_script("window.scrollBy(0,100)")
g=driver.find_elements(By.XPATH,'//img[@class="rg_i Q4LuWd"]')

for i in g:
    source=i.get_attribute('src')
    if source is not None:
        if (source[0:4] == 'http'):
            guitar.append(source)
            
            
for i in range(len(guitar)):
    if i>10:
        break
    print("Downloading {0} of {1} images" .format(i, 10))
    response=requests.get(guitar[i])
    file = open(r"C:\Users\hp\OneDrive\Desktop\down"+str(i)+".jpg","wb")
    file.write(response.content)

# Question 4

In [228]:
driver.get("https://www.flipkart.com")

In [232]:
role3=driver.find_element(By.XPATH,'//input[@class="_3704LK"]')
role3.send_keys('Oneplus Nord')

role4=driver.find_element(By.XPATH,'//button[@class="L0Z3Pu"]')
role4.click()

In [233]:
Company=[]
Smartphone_Name=[]
Colour=[]
RAM=[]
Storage=[]
Primary_Camera=[]
Secondary_Camera=[]
Display_Size=[]
Battery_Capacity=[]
Price=[]
Product_URL=[]

In [234]:
role5=driver.find_elements(By.CLASS_NAME,'_1fQZEK')
for i in role5:
    Product_URL.append(i.get_attribute('href'))

In [235]:
len(Product_URL)

24

In [236]:
for i in Product_URL:
    driver.get(i)
    
    
    try:
        company=driver.find_element(By.XPATH,'//span[@class="B_NuCI"]')
        Company.append(company.text.split('Nord')[0])
    except NoSuchElementException:
        Company.append('-')
        
    
    try:
        smartphone=driver.find_element(By.XPATH,'//span[@class="B_NuCI"]')
        Smartphone_Name.append(smartphone.text.split('(')[0])
    except NoSuchElementException:
        Smartphone_Name.append('-')
        
        
    try:
        colour=driver.find_element(By.XPATH,'//*[@class="_14cfVK"]/tbody/tr[4]/td[2]/ul/li')
        Colour.append(colour.text)
    except NoSuchElementException:
        Colour.append('-')
        
    
    try:
        ram=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li[1]')
        RAM.append(ram.text.split('|')[0])
    except NoSuchElementException:
        RAM.append('-')
        
        
    try:
        storage=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li[1]')
        Storage.append(storage.text.split('|')[1])
    except NoSuchElementException:
        Storage.append('-')
        
    try:
        primary=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li[3]')
        Primary_Camera.append(primary.text.split('|')[0])
    except NoSuchElementException:
        Primary_Camera.append('-')
        
        
    try:
        secondary=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li[3]')
        Secondary_Camera.append(secondary.text)
    except NoSuchElementException:
        Secondary_Camera.append('-')
    
        
    try:
        display=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li[2]')
        Display_Size.append(display.text.split('(')[0])
    except NoSuchElementException:
        Display_Size.append('-')
        
        
    try:
        battery=driver.find_element(By.XPATH,'//*[@class="_2418kt"]/ul/li[4]')
        Battery_Capacity.append(battery.text.split('B')[0])
    except NoSuchElementException:
        Battery_Capacity.append('-')
        
        
    try:
        price=driver.find_element(By.XPATH,'//div[@class="_30jeq3 _16Jk6d"]')
        Price.append(price.text)
    except NoSuchElementException:
        Price.append('-')

In [237]:
print(len(Price),len(Battery_Capacity),len(Display_Size),len(Secondary_Camera),len(Primary_Camera),len(Storage),len(RAM),len(Colour),len(Smartphone_Name),len(Company))

24 24 24 24 24 24 24 24 24 24

In [238]:
df1=pd.DataFrame({"Brand":Company,"Smartphone Name":Smartphone_Name,"Colour":Colour,"RAM":RAM,"Storage":Storage,"Primary Camera":Primary_Camera,"Secondary Camera":Secondary_Camera,"Display Size":Display_Size,"Battery Capacity":Battery_Capacity,"Price":Price,"Product URL":Product_URL})
df1

,Brand,Smartphone Name,Colour,RAM,Storage,Primary Camera,Secondary Camera,Display Size,Battery Capacity,Price,Product URL
0,OnePlus,OnePlus Nord CE 2 Lite 5G,Blue Tide,6 GB RAM,128 GB ROM,64MP Rear Camera,64MP Rear Camera | 16MP Front Camera,16.74 cm,5000 mAh,"₹17,770",https://www.flipkart.com/oneplus-nord-ce-2-lit...
1,OnePlus,OnePlus Nord CE 2 Lite 5G,Black Dusk,6 GB RAM,128 GB ROM,64MP Rear Camera,64MP Rear Camera | 16MP Front Camera,16.74 cm,5000 mAh,"₹17,695",https://www.flipkart.com/oneplus-nord-ce-2-lit...
2,OnePlus,OnePlus Nord 3 5G,Misty Green,16 GB RAM,256 GB ROM,50MP Rear Camera,50MP Rear Camera,17.12 cm,5000 mAh,"₹37,458",https://www.flipkart.com/oneplus-nord-3-5g-mis...
3,OnePlus,OnePlus Nord 3 5G,Tempest Gray,16 GB RAM,256 GB ROM,50MP Rear Camera,50MP Rear Camera,17.12 cm,5000 mAh,"₹37,221",https://www.flipkart.com/oneplus-nord-3-5g-tem...
4,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera | 32MP Front Camera,17.02 cm,4500 mAh,"₹28,999",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
5,OnePlus,OnePlus Nord 3 5G,Tempest Gray,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.12 cm,5000 mAh,"₹32,674",https://www.flipkart.com/oneplus-nord-3-5g-tem...
6,OnePlus,OnePlus Nord 3 5G,Misty Green,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.12 cm,5000 mAh,"₹32,776",https://www.flipkart.com/oneplus-nord-3-5g-mis...
7,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.02 cm,4500 mAh,"₹28,995",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
8,OnePlus,OnePlus Nord 2 5G,Blue Haze,12 GB RAM,256 GB ROM,50MP Rear Camera,50MP Rear Camera,16.33 cm,4500 mAh,"₹34,990",https://www.flipkart.com/oneplus-nord-2-5g-blu...
9,OnePlus,OnePlus Nord 2 5G,Gray Sierra,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,16.33 cm,4500 mAh,"₹29,999",https://www.flipkart.com/oneplus-nord-2-5g-gra...
10,OnePlus,OnePlus Nord,Gray Onyx,6 GB RAM,64 GB ROM,48MP + 8MP,48MP + 8MP | 32MP + 8MP Dual Front Camera,16.36 cm,4115 mAh,"₹23,990",https://www.flipkart.com/oneplus-nord-gray-ony...
11,OnePlus,OnePlus Nord,Blue Marble,12 GB RAM,256 GB ROM,48MP + 8MP,48MP + 8MP | 32MP + 8MP Dual Front Camera,16.36 cm,4115 mAh,"₹28,990",https://www.flipkart.com/oneplus-nord-blue-mar...
12,OnePlus,OnePlus Nord 2 5G,PAC-MAN,12 GB RAM,256 GB ROM,50MP Rear Camera,50MP Rear Camera,16.33 cm,4500 mAh,"₹37,999",https://www.flipkart.com/oneplus-nord-2-5g-pac...
13,"OnePlus NORD CE2 LITE 5G (Blue Tide, 128 GB) ...",OnePlus NORD CE2 LITE 5G,Blue Tide,6 GB RAM,128 GB ROM,64MP Rear Camera,64MP Rear Camera,16.74 cm,5000 mAh,"₹17,999",https://www.flipkart.com/oneplus-nord-ce2-lite...
14,"OnePlus NORD CE2 LITE 5G (Blue, Black, 128 GB)...",OnePlus NORD CE2 LITE 5G,"Blue, Black",6 GB RAM,128 GB ROM,64MP Rear Camera,64MP Rear Camera,16.74 cm,5000 mAh,"₹17,998",https://www.flipkart.com/oneplus-nord-ce2-lite...
15,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.02 cm,4500 mAh,"₹28,999",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
16,OnePlus,OnePlus Nord 2T 5G,Jade Fog,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera | 32MP Front Camera,17.02 cm,4500 mAh,"₹26,578",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
17,OnePlus,OnePlus Nord 2T 5G,Gray Shadow,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.02 cm,4500 mAh,"₹28,988",https://www.flipkart.com/oneplus-nord-2t-5g-gr...
18,OnePlus,OnePlus Nord,Gray Onyx,8 GB RAM,128 GB ROM,48MP + 8MP,48MP + 8MP | 32MP + 8MP Dual Front Camera,16.36 cm,4115 mAh,"₹24,990",https://www.flipkart.com/oneplus-nord-gray-ony...
19,OnePlus,OnePlus Nord CE 3 Lite 5G,Chromatic Gray,8 GB RAM,128 GB ROM,108MP Rear Camera,108MP Rear Camera,17.07 cm,5000 mAh,"₹17,890",https://www.flipkart.com/oneplus-nord-ce-3-lit...
20,OnePlus,OnePlus Nord CE 3 Lite 5G,Pastel Lime,8 GB RAM,128 GB ROM,108MP Rear Camera,108MP Rear Camera,17.07 cm,5000 mAh,"₹18,999",https://www.flipkart.com/oneplus-nord-ce-3-lit...
21,OnePlus,OnePlus Nord CE 3 Lite 5G,Chromatic Gray,8 GB RAM,256 GB ROM,108MP Rear Camera,108MP Rear Camera,17.07 cm,5000 mAh,"₹21,249",https://www.flipkart.com/oneplus-nord-ce-3-lit...
22,OnePlus,OnePlus Nord 2T 5G,Jade Fog,8 GB RAM,128 GB ROM,50MP Rear Camera,50MP Rear Camera,17.02 cm,4500 mAh,"₹27,899",https://www.flipkart.com/oneplus-nord-2t-5g-ja...
23,OnePlus,OnePlus Nord CE 3 Lite 5G,Pastel Lime,8 GB RAM,256 GB ROM,108MP Rear Camera,108MP Rear Camera,17.07 cm,5000 mAh,"₹21,499",https://www.flipkart.com/oneplus-nord-ce-3-lit...

In [243]:
df1.to_csv('question4')

# Question 5

In [35]:
driver.get("https://www.google.com/maps")

In [36]:
role16=driver.find_element(By.XPATH,'//input[@class="searchboxinput xiQnY"]')
role16.send_keys('Delhi')

role17=driver.find_element(By.XPATH,'//div[@class="pzfvzf"]')
role17.click()
time.sleep(5)

In [37]:
Latitude=[]
Longitude=[]

In [38]:
try:
    
    url_string = driver.current_url
    print("URL EXTRACTED: ", url_string)
    lat_lng = re.findall(r'@(.*)data',url_string)
    new=lat_lng[0].split(',')
    Longitude=new[1]
    Latitude=new[0]
    
except NoSuchElementException:
    url_string.append('-')

URL EXTRACTED:  https://www.google.com/maps/place/Delhi/@28.6436846,76.7635598,10z/data=!3m1!4b1!4m6!3m5!1s0x390cfd5b347eb62d:0x37205b715389640!8m2!3d28.7040592!4d77.1024902!16zL20vMDlmMDc?entry=ttu

In [39]:
Latitude

'28.6436846'

In [40]:
Longitude

'76.7635598'

# Question 6

In [41]:
driver.get("https://www.digit.in")

In [42]:
role6=driver.find_element(By.XPATH,'//span[@class="arrow_down laptops"]')
role6.click()

role7=driver.find_element(By.XPATH,'/html/body/div[2]/div/ul/li[2]/div[2]/div/div[1]/span[4]/strong')
role7.click()

role8=driver.find_element(By.XPATH,'/html/body/div[2]/div/ul/li[2]/div[2]/div/div[5]/div/div[2]/a/div')
role8.click()

time.sleep(5)

In [43]:
Lapi_URL=[]
Lapi_name=[]
Weight=[]
OS=[]
Price_Lapi=[]
Processor=[]
Display=[]
Memory=[]

In [44]:
role9=driver.find_elements(By.XPATH,'//span[@class="datahreflink"]')
for i in role9[0:7]:
    Lapi_URL.append(i.get_attribute('data-href'))
    
time.sleep(5)

In [45]:
for i in Lapi_URL:
    driver.get(i)
    
    
    try:
        lapi=driver.find_element(By.XPATH,'//div[@class="heading-wraper"]')
        Lapi_name.append(lapi.text.split('\n')[0])
    except NoSuchElementException:
        Lapi_name.append('-')
        
        
    try:
        display=driver.find_element(By.XPATH,'//*[@class="key_specifications  notspecs "]/div[1]/ul/li[2]/div/p[2]/strong')
        Display.append(display.text)
    except NoSuchElementException:
        Display.append('-')
        
        
    try:
        os=driver.find_element(By.XPATH,'//*[@class="key_specifications  notspecs "]/div[1]/ul/li/div/p[2]/strong')
        OS.append(os.text)
    except NoSuchElementException:
        OS.append('-')
        
        
        
    try:
        processor=driver.find_element(By.XPATH,'//*[@class="key_specifications  notspecs "]/div[1]/ul/li[3]/div/p[2]/strong')
        Processor.append(processor.text)
    except NoSuchElementException:
        Processor.append('-')
        
    try:
        memory=driver.find_element(By.XPATH,'//*[@class="key_specifications  notspecs "]/div[1]/ul/li[4]/div/p[2]/strong')
        Memory.append(memory.text)
    except NoSuchElementException:
        Memory.append('-')
        
        
        
    try:
        price=driver.find_element(By.XPATH,'//*[@class="price_sec"]/div/h2/strong')
        Price_Lapi.append(price.text)
    except NoSuchElementException:
        Price_Lapi.append('-')
        
        
        
    try:
        weight=driver.find_element(By.XPATH,'//*[@class="speci_details"]/div[1]/div[5]/table/tbody/tr[1]/td[3]')
        Weight.append(weight.text)
    except NoSuchElementException:
        Weight.append('-')

In [46]:
print(len(Lapi_URL),len(Weight),len(OS),len(Memory),len(Display),len(Price_Lapi),len(Processor),len(Lapi_name))

7 7 7 7 7 7 7 7

In [47]:
df2=pd.DataFrame({"Name":Lapi_name,"OS":OS,"Processor":Processor,"Display":Display,"Memory":Memory,"Weight In Kg":Weight,"Price":Price_Lapi,"Product URL":Lapi_URL})
df2

,Name,OS,Processor,Display,Memory,Weight In Kg,Price,Product URL
0,HP Omen 17-ck2008TX 13th Gen Core i7-13700HX,Windows 11 Home,13th Gen Intel Core i7-13700HX | 5.0 GHz,"17.3"" (2560 x 1440)",1 TB SSD/16 GB DDR5,2.78,"₹ 269,777",https://www.digit.in/laptops/hp-omen-17-ck2008...
1,MSI GT77 Titan 12UHS-054IN 12th Gen Core i9-12...,Windows 11 Home,12th Gen Intel Core i9-12900HX | 3.6 GHz,"17.3"" (3840 x 2160)",2 TB SSD/64 GB DDR5,3.3,"₹ 499,990",https://www.digit.in/laptops/msi-gt77-titan-12...
2,Lenovo Legion 5i Pro 12th Gen Core i7-12700H (...,Windows 11 Home,12th Gen Intel Core i7-12700H | 4.7 GHz,"16"" (2560 x 1600)",1 TB SSD/32 GB DDR5,3.6,"₹ 218,000",https://www.digit.in/laptops/lenovo-legion-5i-...
3,ASUS ROG Strix Scar 18 G834JZ-N5041WS 13th Gen...,Windows 11 Home,13th Gen Intel Core i9-13980HX | 2.2 GHz,"18"" (1920 x 1200)",1 TB SSD/32 GB DDR5,3.1,"₹ 279,990",https://www.digit.in/laptops/asus-rog-strix-sc...
4,Acer Predator Helios Neo 16 13th Gen Core i7-1...,Windows 11 Home,13th Gen Intel Core i7-13700HX | NA,"16"" (2560 x 1600)",1 TB SSD/16 GB DDR5,2.6,"₹ 149,990",https://www.digit.in/laptops/acer-predator-hel...
5,ASUS ROG Zephyrus G14 Ryzen 9-6900HS (GA402RJZ...,Windows 11 Home,AMD Ryzen 9-6900HS | 4.9 GHz,"14"" (1920 x 1200)",1 TB SSD/16 GB DDR5,1.65,"₹ 156,990",https://www.digit.in/laptops/asus-rog-zephyrus...
6,MSI Cyborg 15 12th Gen Core i7-12650H (A12VF-2...,Windows 11 Home,12th Gen Intel Core i7-12650H | 4.7 GHz,"15.6"" (1920 x 1080)",1 TB SSD/16 GB DDR5,1.98,"₹ 130,990",https://www.digit.in/laptops/msi-cyborg-15-12t...

# Question 7

In [77]:
driver.get("https://www.forbes.com")

In [78]:
role10=driver.find_element(By.XPATH,'//div[@class="_69hVhdY4"]')
role10.click()

time.sleep(2)

In [79]:
role11=driver.find_element(By.XPATH,'//*[@class="mpBfVZz3"]/span[1]')
role11.click()

time.sleep(2)

In [80]:
role12=driver.find_element(By.XPATH,'//*[@class="nZ7gK18V KvNFBOfs"]/div[3]/ul/li/a')
role12.click()

time.sleep(2)

In [81]:
Bill_Name=[]
Net_worth=[]
Age=[]
Country=[]
Source=[]
Industry=[]
Rank=[]

In [82]:
billname=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]')
Bill_Name.append(billname.text.split('\n')[1])

billage=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]')
Age.append(billage.text.split('\n')[3])

billworth=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]')
Net_worth.append(billworth.text.split('\n')[2])

billcountry=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]')
Country.append(billcountry.text.split('\n')[4])

billsource=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]')
Source.append(billsource.text.split('\n')[5])

billindustry=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]')
Industry.append(billindustry.text.split('\n')[6])

billrank=driver.find_element(By.XPATH,'/html/body/div[1]/div[2]/div[3]/div[2]/div[2]/div[2]/div[1]/div[1]/div[1]/div[2]/div[1]/div[1]')
Rank.append(billrank.text.split('\n')[0])

In [83]:
df4=pd.DataFrame({"Rank":Rank,"Billionare Name":Bill_Name,"Net_worth":Net_worth,"Age":Age,"Country":Country,"Source":Source,"Industry":Industry})
df4

,Rank,Billionare Name,Net_worth,Age,Country,Source,Industry
0,1,Bernard Arnault & family,$211 B,74,France,LVMH,Fashion & Retail

In [63]:
driver.get("https://www.forbes.com")

In [64]:
role13=driver.find_element(By.XPATH,'//div[@class="_69hVhdY4"]')
role13.click()

time.sleep(2)

In [68]:
role14=driver.find_element(By.XPATH,'/html/body/div[1]/header/nav/div[1]/div[1]/div/div[2]/ul/li[2]/div[1]')
role14.click()

time.sleep(2)

In [70]:
role15=driver.find_element(By.XPATH,'/html/body/div[1]/header/nav/div[1]/div[1]/div/div[2]/ul/li[2]/div[2]/div[3]/ul/li[1]/a')
role15.click()

time.sleep(2)

In [71]:
Bill_Name=[]
Net_worth=[]
Age=[]
Country=[]
Source=[]
Rank=[]
Industry=[]

In [74]:
try:
    rank=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]')
    for i in rank[0:199]:
        Rank.append(i.text.split('\n')[0])
        
except NoSuchElementException:
    Rank.append('-')


try:
    bill=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]')
    for i in bill[0:199]:
        Bill_Name.append(i.text.split('\n')[1])
        
except NoSuchElementException:
    Bill_Name.append('-')
    
    
try:    
    worth=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]')
    for i in worth[0:199]:
        Net_worth.append(i.text.split('\n')[2])
        
except NoSuchElementException:
    Net_worth.append('-')
    

try:
    age=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]')
    for i in age[0:199]:
        Age.append(i.text.split('\n')[3])
        
except NoSuchElementException:
    Age.append('-')
    
    

try:    
    country=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]')
    for i in country[0:199]:
        Country.append(i.text.split('\n')[4])
        
except NoSuchElementException:
    Country.append('-')
    
    
try:
    source=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]')
    for i in source[0:199]:
        Source.append(i.text.split('\n')[5])
        
except NoSuchElementException:
    Source.append('-')
    
    
        
try:
    industry=driver.find_elements(By.XPATH,'//div[@class="TableRow_row__L-0Km"]')
    for i in industry[0:199]:
        Industry.append(i.text.split('\n')[6])
            
except NoSuchElementException:
    Industry.append('-')

In [75]:
df3=pd.DataFrame({"Rank":Rank,"Billionare Name":Bill_Name,"Net_worth":Net_worth,"Age":Age,"Country":Country,"Source":Source,"Industry":Industry})
df3

,Rank,Billionare Name,Net_worth,Age,Country,Source,Industry
0,2,Elon Musk,$180 B,51,United States,"Tesla, SpaceX",Automotive
1,3,Jeff Bezos,$114 B,59,United States,Amazon,Technology
2,4,Larry Ellison,$107 B,78,United States,Oracle,Technology
3,5,Warren Buffett,$106 B,92,United States,Berkshire Hathaway,Finance & Investments
4,6,Bill Gates,$104 B,67,United States,Microsoft,Technology
...,...,...,...,...,...,...,...
194,195,Jin Baofang,$9.6 B,70,China,Solar panels,Energy
195,195,Luo Liguo & family,$9.6 B,67,China,Chemicals,Manufacturing
196,195,Marijke Mars,$9.6 B,58,United States,"Candy, pet food",Food & Beverage
197,195,Pamela Mars,$9.6 B,62,United States,"Candy, pet food",Food & Beverage
198,195,Valerie Mars,$9.6 B,64,United States,"Candy, pet food",Food & Beverage

In [84]:
df5=pd.concat([df4,df3],ignore_index=True)

df5

,Rank,Billionare Name,Net_worth,Age,Country,Source,Industry
0,1,Bernard Arnault & family,$211 B,74,France,LVMH,Fashion & Retail
1,2,Elon Musk,$180 B,51,United States,"Tesla, SpaceX",Automotive
2,3,Jeff Bezos,$114 B,59,United States,Amazon,Technology
3,4,Larry Ellison,$107 B,78,United States,Oracle,Technology
4,5,Warren Buffett,$106 B,92,United States,Berkshire Hathaway,Finance & Investments
...,...,...,...,...,...,...,...
195,195,Jin Baofang,$9.6 B,70,China,Solar panels,Energy
196,195,Luo Liguo & family,$9.6 B,67,China,Chemicals,Manufacturing
197,195,Marijke Mars,$9.6 B,58,United States,"Candy, pet food",Food & Beverage
198,195,Pamela Mars,$9.6 B,62,United States,"Candy, pet food",Food & Beverage
199,195,Valerie Mars,$9.6 B,64,United States,"Candy, pet food",Food & Beverage

# Question 8

In [161]:
driver.get("https://www.youtube.com/watch?v=IEfBBYmxtIo")
time.sleep(10)

In [162]:
comments=[]
time_comments=[]
upvotes=[]

In [163]:
for _ in range(100):
    driver.execute_script("window.scrollBy(0,1000)")
    time.sleep(10)
    
    
comment=driver.find_elements(By.XPATH,'//yt-formatted-string[@id="content-text"]')
for i in comment[0:500]:
    comments.append(i.text)
    
time_comment=driver.find_elements(By.XPATH,'//yt-formatted-string[@class="published-time-text style-scope ytd-comment-renderer"]')
for i in time_comment[0:500]:
    time_comments.append(i.text)


upvote=driver.find_elements(By.XPATH,'//span[@id="vote-count-middle"]')
for i in upvote[0:500]:
    upvotes.append(i.text)

In [164]:
print(len(comments),len(time_comments),len(upvotes))

500 500 500

In [165]:
df7=pd.DataFrame({"Comments":comments,"Time":time_comments,"Upvotes":upvotes})
df7

,Comments,Time,Upvotes
0,First\nAur ek baat naya show tayyar hai. Ticke...,3 weeks ago,13K
1,No one can beat bassii.,3 weeks ago (edited),18K
2,I have never laughed for continuous 37 minutes...,9 days ago,464
3,"No vulgar jokes, no hurting anyone. Just pure ...",2 weeks ago,933
4,After 5 months i really smiled thanks to you b...,2 days ago,18
...,...,...,...
495,Masterpiece officer,2 weeks ago,
496,"""Mujhe chauk de budhiya""...my favourite line f...",12 days ago,1
497,There is much more loud sound of audience clap...,3 days ago,
498,Bhai sahab the og content of comedy want mor...,2 weeks ago,
499,"Officer, salute rakho. Tummy is cramping from ...",3 days ago,

# Question 9

In [200]:
driver.get("https://www.hostelworld.com")

In [201]:
role18=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[1]/div/div[2]/input')
role18.send_keys('London')
time.sleep(5)

In [202]:
role19=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[1]/div[2]/div/ul/li[2]')
role19.click()
time.sleep(5)

In [203]:
role20=driver.find_element(By.XPATH,'/html/body/div[3]/div/div/div[2]/div[2]/div[2]/div/div/div/div[5]/button')
role20.click()
time.sleep(5)

In [204]:
Property=[]
P_rating=[]
P_review=[]
P_keyword=[]
P_distance=[]
P_price=[]
S_price=[]
P_facility=[]
P_description=[]
P_url=[]

In [208]:
p_url=driver.find_elements(By.XPATH,'//a[@class="nuxt-link"]')
for i in p_url[2:33]:
    P_url.append(i.get_attribute('href'))

In [209]:
len(P_url)

30

In [210]:
p_distance=driver.find_elements(By.XPATH,'//span[@class="distance-description"]')
for i in p_distance:
    P_distance.append(i.text)
    
p_price=driver.find_elements(By.XPATH,'//div[@class="property-accommodation-prices"]')
for i in p_price:
    P_price.append(i.text.split('\n')[1])
    
s_price=driver.find_elements(By.XPATH,'//div[@class="property-accommodation-prices"]')
for i in s_price:
    S_price.append(i.text.split('\n')[2])

In [212]:
for i in P_url:
    driver.get(i)
    
    
    try:
        p_rating=driver.find_element(By.XPATH,'//*[@class="reviews-and-ratings"]/div[1]/div[1]/div[1]')
        P_rating.append(p_rating.text)
        
    except NoSuchElementException:
        P_rating.append('-')


    try:
        p_review=driver.find_element(By.XPATH,'//*[@class="reviews-and-ratings"]/div[1]/div[1]/div[2]/div[2]')
        P_review.append(p_review.text)

    except NoSuchElementException:
        P_review.append('-')


    try:
        prop=driver.find_element(By.XPATH,'//div[@class="title-2"]')
        Property.append(prop.text)

    except NoSuchElementException:
        Property.append('-')


    try:
        p_facility=driver.find_element(By.XPATH,'//*[@class="facilities-container"]/ul[1]/li[1]/ul[1]')
        P_facility.append(p_facility.text)

    except NoSuchElementException:
        P_facility.append('-')

    try:
        p_description=driver.find_element(By.XPATH,'//*[@class="description-container"]/div[1]/div[2]')
        P_description.append(p_description.text)
        
    except NoSuchElementException:
        P_description.append('-')


    try:
        p_keyword=driver.find_element(By.XPATH,'//*[@class="reviews-and-ratings"]/div[1]/div[1]/div[2]/div/span')
        P_keyword.append(p_keyword.text)
    except NoSuchElementException:
        P_keyword.append('-')

In [213]:
df6=pd.DataFrame({"Hostel Name":Property,"Distance from the city centre":P_distance,"Ratings":P_rating,"Total reviews":P_review,"overall reviews":P_keyword,"privates from price":P_price,"dorms from price":S_price,"facilities":P_facility,"description":P_description})
df6

,Hostel Name,Distance from the city centre,Ratings,Total reviews,overall reviews,privates from price,dorms from price,facilities,description
0,YHA London Earls Court,- 5.1km from city centre,9.1,1463 Total Reviews,Superb,"₹15,835",No Dorms Available,Linen Included Free WiFi,YHA London Earls Court has been recommended by...
1,YHA London St Pauls,- 1.9km from city centre,8.8,2089 Total Reviews,Fabulous,"₹14,780",No Dorms Available,Linen Included Free City Maps Free WiFi,If your main interest in London is museums and...
2,Pickwick Hall,- 2.3km from city centre,8.7,2692 Total Reviews,Fabulous,"₹13,724",No Dorms Available,Free Breakfast Linen Included Free Internet Ac...,Pickwick Hall provides accommodation for touri...
3,Strand Continental,- 1.3km from city centre,6.2,976 Total Reviews,Good,"₹7,566",Dorms From,Common Room Hot Showers Iron / Ironing Board S...,"Welcome to one of London's cheapest, friendlie..."
4,YHA London Central,- 2.9km from city centre,8.4,4766 Total Reviews,Fabulous,"₹23,225",No Dorms Available,Linen Included Free City Maps Free WiFi,YHA London Central is often mentioned by our g...
5,Mornington Camden,- 4.1km from city centre,6.7,56 Total Reviews,Good,Dorms From,"₹4,000",Linen Included Free City Maps Towels Included ...,Female Only Mornington Camden Hostel is a high...
6,Bell House Hostel,- 4.2km from city centre,7.6,80 Total Reviews,Very Good,Dorms From,"₹2,914",Linen Included Free WiFi,"Boasting a bar and a shared lounge, Bell House..."
7,"PubLove @ The Steam Engine, Waterloo",- 0.5km from city centre,8.0,409 Total Reviews,Fabulous,Dorms From,"₹3,976",Linen Included Free City Maps Free WiFi,"The Steam Engine, Bestplace Inn is a great hos..."
8,London Waterloo Hostel,- 0.7km from city centre,5.8,2542 Total Reviews,Rating,"₹8,393",Dorms From,Linen Included Free City Maps Free WiFi Free I...,The London Waterloo Hostel 16-40 years in DORM...
9,Selina Camden,- 5.5km from city centre,8.7,54 Total Reviews,Fabulous,"₹16,426",No Dorms Available,Linen Included Towels Included Free WiFi Free ...,"Among underground music venues, innovative mus..."
10,Generator London,- 3km from city centre,7.6,7634 Total Reviews,Very Good,"₹13,729",Dorms From,Linen Included Free City Maps Free WiFi Free I...,Hostelworld guests have said Generator Hostel ...
11,St Christopher's Village,- 1.8km from city centre,8.1,12298 Total Reviews,Fabulous,-10%,Dorms From,Linen Included Free WiFi Free Internet Access,Hostelworld visitors have said St Christopher'...
12,Safestay London Elephant & Castle,- 1.7km from city centre,7.2,5040 Total Reviews,Very Good,Dorms From,"₹2,696",Linen Included Free WiFi,Safestay at Elephant and Castle is located in ...
13,St Christopher's Inn - London Bridge,- 1.8km from city centre,7.8,3528 Total Reviews,Very Good,-10%,Dorms From,Linen Included Free City Maps Free WiFi Free I...,St Christopher's Inn - London Bridge is all ab...
14,Astor Victoria,- 1.8km from city centre,7.1,14999 Total Reviews,Very Good,Dorms From,"₹2,393",Linen Included Free City Maps Free WiFi Free I...,Note: 18-40 yrs old only. Astor Victoria won 1...
15,Onefam Notting Hill by Hostel One,- 5.5km from city centre,9.7,2175 Total Reviews,Superb,"₹17,764",Dorms From,Linen Included Free WiFi Free Internet Access,The perfect place for solo travelers to connec...
16,Urbany Hostel London,- 5.4km from city centre,9.5,850 Total Reviews,Superb,"₹16,381",Dorms From,Linen Included Free WiFi,"Welcome to Urbany Hostel London, our first int..."
17,Barmy Badger Backpackers,- 5.5km from city centre,9.0,1955 Total Reviews,Superb,"₹12,052",Dorms From,Free Breakfast Linen Included Free City Maps F...,The Badger is unique for London in that we hav...
18,Kabannas London St Pancras,- 3.3km from city centre,9.1,2872 Total Reviews,Superb,Dorms From,"₹3,660",Linen Included Free City Maps Free WiFi,Kabannas London St Pancras has friendly recept...
19,Wombat's City Hostel London,- 3.6km from city centre,9.0,15139 Total Reviews,Superb,Privates From,"₹22,361",Linen Included Free City Maps Free WiFi Free I...,A safe haven in the middle of the metropolis: ...
20,"PubLove @ The Green Man, Paddington",- 4.3km from city centre,5.5,450 Total Reviews,Rating,"₹26,603",Dorms From,Linen Included Free City Maps Free WiFi,The Green Man Bestplace Inn is next door to Ed...
21,PubLove @ The Rose & Crown,- 1.6km from city centre,7.7,198 Total Reviews,Very Good,Dorms From,"₹4,223",Linen Included Free City Maps Free WiFi,"Food & culture lovers, assemble!\nThe Rose & C..."
22,Clink261,- 3.2km from city centre,8.2,348 Total Reviews,Fabulous,Dorms From,"₹4,020",Linen Included Free City Maps Free WiFi,Clink261 is near King's Cross St Pancras stati...
23,Astor Museum Inn,- 2.2km from city centre,8.2,9298 Total Reviews,Fabulous,Dorms From,"₹2,569",Linen Included Free City Maps Free WiFi,Note: 18-40 yrs old only. Astor Museum won 1st...
24,Phoenix Hostel,- 4.2km from city centre,7.9,4316 Total Reviews,Very Good,-5%,Dorms From,Linen Included Free City Maps Free WiFi Free I...,"The Phoenix Bar & Hostel, housed in a homely E..."
25,No.8 Willesden Hostel London,- 10km from city centre,6.5,5056 Total Reviews,Good,Dorms From,"₹1,860",Linen Included Free WiFi,At No.8 we take pride in our Customer Service ...
26,No.8 Seven Sisters,- 9km from city centre,5.2,4040 Total Reviews,Rating,Dorms From,"₹1,754",Linen Included Free WiFi,"For Great Facilities, Comfort & Affordability ..."
27,Kensal Green Backpackers,- 8.2km from city centre,5.2,3721 Total Reviews,Rating,"₹9,364",Dorms From,Linen Included Free City Maps,Kensal Green Backpackers is a legendary hostel...
28,Queen Elizabeth Chelsea,- 5.7km from city centre,7.3,3535 Total Reviews,Very Good,Dorms From,"₹3,096",Linen Included Free City Maps Free WiFi Free I...,PLEASE NOTE WE ONLY ACCEPT GUESTS FROM THE AGE...
29,-,- 6.5km from city centre,-,-,-,Privates From,"₹229,357",-,-

In [214]:
print(len(Property),len(P_distance),len(P_rating),len(P_review),len(P_keyword),len(P_price),len(S_price),len(P_facility),len(P_url),len(P_description))

30 30 30 30 30 30 30 30 30 30